### ISSUE TITLE
eigen?

### ISSUE THREAD

**Issue by seghier** [aromanro/LatticeBoltzmann#8]
Hello
How to add eigen?

```
#include <eigen\eigen>

Error (active)	E1696	cannot open source file "eigen\eigen"	LatticeBoltzmann
```

**Comment by aromanro** [comment]
Get it from here: https://eigen.tuxfamily.org/index.php?title=Main_Page

Unpack it somewhere (the VC++ project has setting for it in C:\LIBs or something like that, check the project options for that).

If you put it in some other place you need to set the project include path properly. Eigen is an 'include only' library so nothing more should be done about it that that.

**Comment by seghier** [comment]
Thank you, i compile it but i don't see any effect, maybe problem of GPU?

**Comment by aromanro** [comment]
Could you be a little more specific?
I assume you managed to run it... if that's the case, you need to load a file that contains a mask of the object you want to have in there.
There is a blog entry with a description and even a video that shows its functionality: https://youtu.be/CIVWTfbblvI?si=kQRwkLBsFpdCR7-x

**Comment by seghier** [comment]
Thanks
That what i get when i run it, an error an nothing happened even
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0766	exception specification for virtual function "COleControlSite::XBoundObjectSite::QueryInterface" is incompatible with that of overridden function "IBoundObjectSite::QueryInterface"	LatticeBoltzmann	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\atlmfc\include\afxocc.h	442	
```


![image](https://github.com/aromanro/LatticeBoltzmann/assets/6026588/1681bafd-a612-419b-9d04-d39a6590a8d9)

My laptop:
`Hp 8770w Quadro K4000M`

**Comment by aromanro** [comment]
Build it in release mode, debug is very slow (especially on a laptop).

That exception is odd, though.
